"""
HTML reporter – REQ-014.

Renders a human-readable report from drift.json / coverage.json artifacts.
Works directly from raw dicts (no dataclass dependency).
"""
from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Environment, BaseLoader


_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DriftDetect Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; color: #222; }
  h1 { color: #1a56db; }
  h2 { border-bottom: 2px solid #e5e7eb; padding-bottom: .3rem; }
  .badge-drift { background: #fee2e2; color: #b91c1c; padding: 2px 8px; border-radius: 9999px; font-size: .85em; }
  .badge-ok    { background: #d1fae5; color: #065f46; padding: 2px 8px; border-radius: 9999px; font-size: .85em; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { text-align: left; padding: .5rem .75rem; border: 1px solid #e5e7eb; }
  th { background: #f9fafb; }
  tr:hover { background: #f3f4f6; }
  .sev-bar { background: #e5e7eb; border-radius: 4px; height: 10px; position: relative; }
  .sev-fill { height: 10px; border-radius: 4px; }
</style>
</head>
<body>
<h1>🔍 DriftDetect Report</h1>

{% if drift %}
<h2>Drift Detection — Window: {{ drift.metadata.window_id }}</h2>

{% set global = drift.global %}
{% set detected = global.drift_detected %}
{% if detected %}
  <p><span class="badge-drift">⚠ DRIFT DETECTED</span>
  &nbsp; Max severity: {{ "%.3f"|format(global.max_severity) }}
  &nbsp; Drifted features: {{ global.drifted_count }}
  &nbsp; Reasons: {{ global.reasons | join(", ") }}
  </p>
{% else %}
  <p><span class="badge-ok">✅ No Drift Detected</span>
  &nbsp; Max severity: {{ "%.3f"|format(global.max_severity) }}
  </p>
{% endif %}

{% set schema = drift.schema_drift %}
{% if schema and (schema.added or schema.removed or schema.type_changed) %}
<h3>⚠ Schema Drift</h3>
<ul>
  {% for c in schema.added %}<li>Added column: <b>{{ c }}</b></li>{% endfor %}
  {% for c in schema.removed %}<li>Removed column: <b>{{ c }}</b></li>{% endfor %}
  {% for c in schema.type_changed %}<li>Type changed: <b>{{ c.name }}</b> ({{ c.baseline }} → {{ c.window }})</li>{% endfor %}
</ul>
{% endif %}

<h3>Top Features by Severity</h3>
<table>
  <thead>
    <tr><th>Rank</th><th>Feature</th><th>Severity</th><th>Drifted?</th><th>Type</th><th>Key Metric</th></tr>
  </thead>
  <tbody>
  {% for item in drift.feature_ranking[:20] %}
    {% set fname = item.feature %}
    {% set f = drift.features[fname] %}
    <tr>
      <td>{{ loop.index }}</td>
      <td><b>{{ fname }}</b></td>
      <td>
        <div class="sev-bar">
          <div class="sev-fill" style="width:{{ (f.severity * 100)|int }}%; background:{% if f.drifted %}#ef4444{% else %}#22c55e{% endif %};"></div>
        </div>
        {{ "%.3f"|format(f.severity) }}
      </td>
      <td>{% if f.drifted %}<span class="badge-drift">Yes</span>{% else %}<span class="badge-ok">No</span>{% endif %}</td>
      <td>{{ f.type }}</td>
      <td>
        {% if f.metrics %}
          {% if f.type == "numeric" %}
            KS={{ "%.3f"|format(f.metrics.get("ks", 0)) }}
            &nbsp; WD={{ "%.3f"|format(f.metrics.get("wasserstein", 0)) }}
          {% else %}
            JS={{ "%.3f"|format(f.metrics.get("js", 0)) }}
          {% endif %}
        {% else %}—{% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if coverage %}
<h2>Coverage Report</h2>
{% set m = coverage.metrics %}
<table>
  <thead><tr><th>Metric</th><th>Value</th></tr></thead>
  <tbody>
    <tr><td>FPR</td><td>{% if m.FPR is not none %}{{ "%.3f"|format(m.FPR) }}{% else %}N/A{% endif %}</td></tr>
    <tr><td>Power (overall)</td><td>{% if m.power_overall is not none %}{{ "%.3f"|format(m.power_overall) }}{% else %}N/A{% endif %}</td></tr>
    {% for t, p in m.power_by_type.items() %}
    <tr><td>Power [{{ t }}]</td><td>{{ "%.3f"|format(p) }}</td></tr>
    {% endfor %}
    {% if m.TTD_summary %}
    <tr><td>TTD median</td><td>{% if m.TTD_summary.median is not none %}{{ m.TTD_summary.median }}{% else %}N/A{% endif %}</td></tr>
    {% endif %}
  </tbody>
</table>

<h3>Missed Events ({{ coverage.missed_events|length }})</h3>
{% if coverage.missed_events %}
<table>
  <thead><tr><th>Event ID</th><th>Type</th><th>Start Window</th><th>Features</th></tr></thead>
  <tbody>
  {% for e in coverage.missed_events %}
    <tr>
      <td>{{ e.event_id }}</td>
      <td>{{ e.type }}</td>
      <td>{{ e.start_window }}</td>
      <td>{{ e.affected_features | join(", ") }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <p><span class="badge-ok">All events detected</span></p>
{% endif %}
{% endif %}

<footer style="margin-top:3rem;color:#9ca3af;font-size:.8em;">Generated by DriftDetect</footer>
</body>
</html>
"""


def render_report(drift: dict | None = None, coverage: dict | None = None) -> str:
    """Render an HTML report string from raw artifact dicts (REQ-014)."""
    env = Environment(loader=BaseLoader())
    template = env.from_string(_REPORT_TEMPLATE)
    return template.render(drift=drift, coverage=coverage)


def save_report(
    path: str,
    drift: dict | None = None,
    coverage: dict | None = None,
) -> None:
    html = render_report(drift=drift, coverage=coverage)
    Path(path).write_text(html, encoding="utf-8")


def save_report_from_files(
    out_path: str,
    drift_path: str | None = None,
    coverage_path: str | None = None,
) -> None:
    """Load artifacts from JSON files and write HTML report."""
    drift = json.loads(Path(drift_path).read_text(encoding="utf-8")) if drift_path else None
    coverage = json.loads(Path(coverage_path).read_text(encoding="utf-8")) if coverage_path else None
    save_report(out_path, drift=drift, coverage=coverage)
